/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    multiplyC
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_Main_multiplyC
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     Main
 * Method:    createMatrixC
 * Signature: (LMatrix;)J
 */
JNIEXPORT jlong JNICALL Java_Main_createMatrixC
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Main
 * Method:    freeMatrixC
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Main_freeMatrixC
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Main
 * Method:    printMatrixC
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Main_printMatrixC
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
