/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorldJNI */

#ifndef _Included_HelloWorldJNI
#define _Included_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorldJNI
 * Method:    eatMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloWorldJNI_eatMemory
  (JNIEnv *, jobject);

/*
 * Class:     HelloWorldJNI
 * Method:    allocate1KB
 * Signature: (LBean;)V
 */
JNIEXPORT void JNICALL Java_HelloWorldJNI_allocate1KB
  (JNIEnv *, jobject, jobject);

/*
 * Class:     HelloWorldJNI
 * Method:    callMethods
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloWorldJNI_callMethods
  (JNIEnv *, jobject);

/*
 * Class:     HelloWorldJNI
 * Method:    getStringLen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_HelloWorldJNI_getStringLen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     HelloWorldJNI
 * Method:    beanToString
 * Signature: (LBean;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HelloWorldJNI_beanToString
  (JNIEnv *, jobject, jobject);

/*
 * Class:     HelloWorldJNI
 * Method:    createNewBean
 * Signature: (Ljava/lang/String;Z)LBean;
 */
JNIEXPORT jobject JNICALL Java_HelloWorldJNI_createNewBean
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     HelloWorldJNI
 * Method:    setBean
 * Signature: (LBean;LBean;)V
 */
JNIEXPORT void JNICALL Java_HelloWorldJNI_setBean
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     HelloWorldJNI
 * Method:    allocateNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_HelloWorldJNI_allocateNativeStruct
  (JNIEnv *, jobject);

/*
 * Class:     HelloWorldJNI
 * Method:    getStructValueInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_HelloWorldJNI_getStructValueInt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     HelloWorldJNI
 * Method:    getStructValueString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HelloWorldJNI_getStructValueString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     HelloWorldJNI
 * Method:    freeStruct
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_HelloWorldJNI_freeStruct
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
